### ISSUE TITLE
[QA][auth]

### ISSUE THREAD

**Issue by zelabstudio** [ynov-2024-m1-team-5/front#30]
- Login 
  - J'essaie de me loguer en rentrant un email et mdp inconnu 
     => Je n'ai pas d'erreur et j'arrive sur le shop
     => Logout est visible sur la nav
     => Il faudrait afficher les erreurs
- Register : 
    => J'essaie de m'inscrire avec un utilisateur déjà inscrit, je n'ai pas d'erreurs qui s'affichent, rien ne se passe   
    =>Je m'inscrit avec un nouvel email, je valide, rien ne se passe

**Comment by aminataCmd** [comment]
"Je n'ai pas d'erreur et j'arrive sur le shop"
"Il faudrait afficher les erreurs"
COTE BACK:
  - send error message
COTE FRONT
 - display the error message
"J'essaie de m'inscrire avec un utilisateur déjà inscrit, je n'ai pas d'erreurs qui s'affichent, rien ne se passe"
COTE FRONT : 
 - send error

**Comment by aminataCmd** [comment]
Ce qu'il reste:
"Je m'inscrit avec un nouvel email, je valide, rien ne se passe" => inscription + connection + redirection vers la page /shop
